spring:
  cloud:
    config:
      allow-override: true
      override-none: false
      override-system-properties: false

# eureka:
#   client:
#     service-url:
#       defaultZone: http://localhost:8102/eureka/
# spring:
#   profiles: secure
#   security:
#     user:
#       name: "user"
#       password: "password"
# eureka:
#   instance:
#     metadata-map:
#       user.name: "user"         #These two are needed so that the server
#       user.password: "password" #can access the protected client endpoints

# eureka: 
#   instance:
#     leaseRenewalIntervalInSeconds: 10
#     health-check-url-path: /actuator/health
#     metadata-map:
#       startup: ${random.int}    #needed to trigger info and endpoint update after restart
#   client:
#     registryFetchIntervalSeconds: 5
#     serviceUrl:
#       defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"  
#   endpoint:
#     health:
#       show-details: ALWAYS




