server:
  port: 8301

spring:
  cloud:
    config:
      allow-override: true
      override-none: true


eureka:
  client:
    service-url:
      default-zone: http://localhost:8102/eureka/

management:
  security:
    enabled: false



